### ISSUE TITLE
Redis ConnectionError

### ISSUE THREAD

**Issue by artyemk** [pm-str/QuestBot#2]
After running docker-compose up I got this error:
`redis.exceptions.ConnectionError: Error -2 connecting to redis:6379. Name or service not known.
ERROR: Service 'web' failed to build: The command '/bin/sh -c python manage.py makemigrations' returned a non-zero code: 1`
What shoud I do?

**Comment by pm-str** [comment]
This issue has been fixed in the [65769ae](https://github.com/pm-str/QuestBot/commit/34c42a25e8400060a80e1a234ca7bc7a265769ae)
